-- ============================================
-- Liene QA 管理平台 — 入职指南模块建表脚本
-- 请在 Supabase SQL Editor 中执行
-- ============================================

-- 1. 创建主表
CREATE TABLE IF NOT EXISTS onboarding_docs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT NOT NULL DEFAULT '环境配置',
  title TEXT NOT NULL,
  icon TEXT DEFAULT 'ti-book',
  content TEXT NOT NULL DEFAULT '',
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. 启用 RLS
ALTER TABLE onboarding_docs ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE id = auth.uid()
      AND role = 'admin'
  );
$$;

REVOKE ALL ON FUNCTION public.is_admin() FROM public;
GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated;

-- 3. 登录成员可读，管理员可写；禁止匿名访问
DROP POLICY IF EXISTS "Anyone can read onboarding_docs" ON public.onboarding_docs;
DROP POLICY IF EXISTS "Admins can insert onboarding_docs" ON public.onboarding_docs;
DROP POLICY IF EXISTS "Admins can update onboarding_docs" ON public.onboarding_docs;
DROP POLICY IF EXISTS "Admins can delete onboarding_docs" ON public.onboarding_docs;
DROP POLICY IF EXISTS onboarding_docs_read_authenticated ON public.onboarding_docs;
DROP POLICY IF EXISTS onboarding_docs_write_admin ON public.onboarding_docs;

CREATE POLICY onboarding_docs_read_authenticated
  ON public.onboarding_docs FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY onboarding_docs_write_admin
  ON public.onboarding_docs FOR ALL
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

REVOKE ALL ON public.onboarding_docs FROM anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.onboarding_docs TO authenticated;
DO $$
BEGIN
  IF to_regclass('public.onboarding_docs_id_seq') IS NOT NULL THEN
    GRANT USAGE, SELECT ON SEQUENCE public.onboarding_docs_id_seq TO authenticated;
  END IF;
END
$$;

-- 5. 预填默认数据（中文 Markdown，可以后续在页面上修改）
INSERT INTO onboarding_docs (category, title, icon, content, sort_order) VALUES
(
  '环境配置',
  'Mac 开发环境总览',
  'ti-brand-apple',
  E'## 必备工具\n\n| 工具 | 安装方式 | 说明 |\n|------|----------|------|\n| Homebrew | 官网安装 | macOS 包管理器 |\n| Python 3.11.9 | `pyenv install 3.11.9` | 使用 pyenv 管理版本 |\n| Node.js 22 | `nvm install 22` | 使用 nvm 管理版本 |\n| Git | `brew install git` | 版本控制 |\n| VS Code | 官网下载 | 推荐编辑器 |\n\n## 验证环境\n\n```bash\npython --version   # Python 3.11.9\nnode --version     # v22.x.x\ngit --version      # 2.x.x\n```',
  1
),
(
  '环境配置',
  'Appium 移动端自动化环境',
  'ti-device-mobile',
  E'## 环境依赖\n\n```bash\n# 安装 Appium 3.4.0\nnpm install -g appium@3.4.0\n\n# 安装 UiAutomator2 驱动（Android）\nappium driver install uiautomator2\n\n# 安装 XCUITest 驱动（iOS）\nappium driver install xcuitest\n\n# 验证\nappium driver list\n```\n\n## Android 环境\n\n- 安装 Android Studio\n- 配置 ANDROID_HOME 环境变量\n- 开启手机的「开发者选项」和「USB 调试」\n\n## iOS 环境\n\n- 安装 Xcode（App Store）\n- 安装 Carthage：`brew install carthage`\n- 信任开发者证书',
  2
),
(
  '环境配置',
  '项目代码拉取与安装',
  'ti-git-branch',
  E'## 克隆仓库\n\n```bash\n# 移动端自动化框架\ngit clone https://github.com/ZiHan-QA/liene-app-automation.git\ncd liene-app-automation\n\n# 创建虚拟环境并安装依赖\npython -m venv venv\nsource venv/bin/activate\npip install -r requirements.txt\n```\n\n## 配置环境变量\n\n在项目根目录创建 `.env` 文件：\n\n```\nVISION_API_KEY=你的AI视觉API密钥\nSUPABASE_URL=https://pgpnyrglrromqqjnvaix.supabase.co\nSUPABASE_KEY=你的anon key\n```\n\n> ⚠️ `.env` 文件末尾不要有空行，否则 key 解析会失败',
  3
),
(
  '常用命令',
  'Git 常用命令',
  'ti-git-merge',
  E'## 日常操作\n\n```bash\ngit status                  # 查看状态\ngit pull                    # 拉取最新代码\ngit add .                   # 暂存所有修改\ngit commit -m "描述"        # 提交\ngit push                    # 推送到远端\n```\n\n## 分支操作\n\n```bash\ngit branch                  # 查看本地分支\ngit checkout -b feat/xxx    # 创建并切换新分支\ngit merge feat/xxx          # 合并分支\n```\n\n## 回退操作\n\n```bash\ngit log --oneline           # 查看提交历史\ngit reset --soft HEAD~1     # 撤销最近一次 commit（保留修改）\ngit checkout -- 文件名      # 撤销文件修改\n```',
  1
),
(
  '常用命令',
  'pytest 测试命令',
  'ti-test-pipe',
  E'## 运行测试\n\n```bash\n# 运行全部测试\npytest\n\n# 运行冒烟测试\npytest tests/smoke/\n\n# 运行指定文件\npytest tests/smoke/test_login.py\n\n# 指定平台运行\npytest --platform=android\npytest --platform=ios\n\n# 生成 Allure 报告\npytest --alluredir=reports/allure-results\nallure serve reports/allure-results\n```\n\n## 常用参数\n\n| 参数 | 说明 |\n|------|------|\n| `-v` | 详细输出 |\n| `-s` | 显示 print 输出 |\n| `-k "关键词"` | 按名称筛选用例 |\n| `-m "标记"` | 按标记筛选（smoke/regression） |\n| `--maxfail=1` | 首次失败后停止 |',
  2
),
(
  '常用命令',
  'ADB 常用命令',
  'ti-terminal-2',
  E'## 设备连接\n\n```bash\nadb devices                 # 查看已连接设备\nadb -s <UDID> shell         # 指定设备\nadb tcpip 5555              # 开启无线调试\nadb connect <IP>:5555       # 无线连接\n```\n\n## 截图与录屏\n\n```bash\nadb shell screencap /sdcard/screen.png\nadb pull /sdcard/screen.png .\nadb shell screenrecord /sdcard/demo.mp4\n```\n\n## 应用管理\n\n```bash\nadb install app.apk         # 安装应用\nadb uninstall com.hannto.fennel.overseas  # 卸载\nadb shell pm list packages  # 列出所有包\n```\n\n## 查看日志\n\n```bash\nadb logcat                  # 实时日志\nadb logcat | grep -i "hannto"  # 过滤关键词\n```',
  3
),
(
  '产品矩阵',
  '产品型号速查表',
  'ti-apps',
  E'## 产品矩阵\n\n| 内部代号 | 海外产品名 | 国内产品名 | 备注 |\n|----------|-----------|-----------|------|\n| **Fennel** | Liene Photo Printer | 极印照片打印机 | 主力照片打印机 |\n| **Kiwi** | Portable Photo Printer | 口袋照片打印机 | 便携式 |\n| **Laurel** | Liene Amber M110/M210 | 极印照片打印机N2 | 第二代 |\n| **Cumin** | Liene Pearl N200 Pro | 极印打印机N3 | 第三代旗舰 |\n| **Perilla** | Liene PixCut S1 | 极印裁切打印机S1 | 裁切一体 |\n| **Gemini** | StickerPix Print+Cut | 待补充 | 贴纸打印 |\n\n## APP 信息\n\n| 属性 | 值 |\n|------|-----|\n| 包名 | `com.hannto.fennel.overseas` |\n| 支持语言 | 17 种 |\n| 测试设备(Android) | vivo V2509A (Android 16) |\n| 测试设备(iOS) | iPhone 13 Pro Max (iOS 16.6.1) |',
  1
),
(
  '产品矩阵',
  'APP 功能模块概览',
  'ti-layout-grid',
  E'## 主要功能模块\n\n1. **照片打印** — 选择照片、编辑、打印\n2. **证件照** — 多种规格证件照制作\n3. **AR 照片** — AR 视频照片\n4. **拼图** — 多图拼接打印\n5. **设备连接** — Wi-Fi/蓝牙配网\n6. **耗材管理** — 色带/相纸余量查看\n7. **个人中心** — 账号、设置、关于\n\n## 测试重点\n\n- 多语言 UI 验证（17 种语言）\n- 设备配网流程（Wi-Fi / 蓝牙）\n- 打印流程端到端\n- 耗材状态同步\n- 跨平台一致性（iOS vs Android）',
  2
),
(
  '团队信息',
  '团队架构与角色',
  'ti-users',
  E'## 团队概览\n\n- **团队规模**：约 15 人\n- **公司**：Hannto Technology（汉图科技）\n- **QA 负责人**：王姿翰（Zihan）\n\n## 主要角色\n\n| 角色 | 职责 |\n|------|------|\n| QA 工程师 | 功能测试、自动化测试、用例编写 |\n| 产品经理 | PRD 编写、需求管理 |\n| 前端开发 | APP 前端（Flutter） |\n| 后端开发 | 云服务、API |\n| 嵌入式开发 | 打印机固件 |\n| 设计师 | UI/UX 设计 |\n\n## QA 工作流\n\n1. PRD 评审 → 理解需求\n2. 编写测试用例 → PingCode\n3. 功能测试 → 手动 + 自动化\n4. BUG 提交 → PingCode\n5. 回归验证 → 自动化回归\n6. 发布验证 → 冒烟测试',
  1
),
(
  '账号工具',
  '必备账号与工具',
  'ti-key',
  E'## 内部平台\n\n| 平台 | 地址 | 用途 |\n|------|------|------|\n| PingCode | 公司内部 | 用例管理 / BUG 跟踪 |\n| Supabase | https://supabase.com | 数据库 / 认证 |\n| GitHub | https://github.com/ZiHan-QA | 代码仓库 |\n| 管理平台 | https://zihan-qa.github.io/Hannto-Liene | QA 管理平台 |\n\n## 开发工具\n\n| 工具 | 用途 |\n|------|------|\n| VS Code | 代码编辑 |\n| Android Studio | Android 开发/调试 |\n| Xcode | iOS 开发/调试 |\n| Appium Inspector | 元素定位 |\n| Postman | API 测试 |\n| Charles | 抓包工具 |\n\n## AI 工具\n\n| 工具 | 用途 |\n|------|------|\n| Kimi (kimi-k2.6) | AI 视觉断言 |\n| 通义千问 (qwen-plus) | PRD 需求拆解 |\n| 阿里云百炼 | QA Pipeline 工具 |',
  1
);
